### ISSUE TITLE
Retrieve CellProfiler pipelines for the Cell Painting datasets

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/cell-health#146]
For the analysis pipeline

- [x] Identify one plate barcode per cell line @gwaygenomics 
- [x] Retrieve the `Experiment.csv` file for any one image in each of the 3 plates e.g. https://imaging-platform.s3.us-east-1.amazonaws.com/projects/2015_07_01_Cell_Health_Vazquez_Cancer_Broad/workspace/analysis/CRISPR_PILOT_B1/SQ00014610/analysis/A01-1/Experiment.csv @gwaygenomics 
- [x] Extract the pipeline from the CSV file by hand (e.g. see [SQ00014610.txt](https://github.com/broadinstitute/cell-health/files/5356847/SQ00014610.txt); this was extracted from the CSV above)
- [x] Compare the 3 pipelines; they are very likely identical, in which case keep just one and name it `analysis.cppipe` else name each by the cell type e.g. `analysis_u2os.cppipe`
- [x] Compare with https://github.com/broadinstitute/imaging-platform-pipelines/blob/master/cellpainting_a549_20x_phenix_bin1/analysis.cppipe and if it is identical, then just use this version instead (there will be some difference wrt load path etc, which can be ignored)

For the illum pipeline

- [x] I'm 100% sure it's the same pipeline we've used for LINCS Cell Painting Pilot https://github.com/broadinstitute/imaging-platform-pipelines/blob/master/cellpainting_a549_20x_phenix_bin1/illum.cppipe so there's nothing to be done here @gwaygenomics

**Comment by hkhawar** [comment]
@gway @shntnu  Only single pipeline is used for all three different cell lines. I have have compared pipelines from following plates

<img width="425" alt="Screen Shot 2020-10-13 at 12 41 30 PM" src="https://user-images.githubusercontent.com/36200793/95896379-c4312800-0d51-11eb-8769-49690971d5ae.png">

Here below is the the final analysis pipe. 

[analysis.cppipe.zip](https://github.com/broadinstitute/cell-health/files/5373116/analysis.cppipe.zip)


This pipeline is identical to [https://github.com/broadinstitute/imaging-platform-pipelines/blob/master/cellpainting_a549_20x_phenix_bin1/analysis.cppipe](url). Only difference is ordering of couple of modules are different. We can this version as well.

**Comment by shntnu** [comment]
We are all set. 
@gwaygenomics, here's what we need
- Illum pipeline: https://github.com/broadinstitute/imaging-platform-pipelines/blob/71b3e1a56916185d5bfb0d6f4ce99a43d240bbe6/cellpainting_a549_20x_phenix_bin1/analysis.cppipe
- Analysis pipeline: https://github.com/broadinstitute/imaging-platform-pipelines/blob/71b3e1a56916185d5bfb0d6f4ce99a43d240bbe6/cellpainting_a549_20x_phenix_bin1/illum.cppipe

**Comment by shntnu** [comment]
Version of CellProfiler used is available in the `Experiment.csv` file (extracted into the SQ00014610.txt file below):

>  Extract the pipeline from the CSV file by hand (e.g. see [SQ00014610.txt](https://github.com/broadinstitute/cell-health/files/5356847/SQ00014610.txt); this was extracted from the CSV above)


```
CellProfiler Pipeline: http://www.cellprofiler.org
Version:3
DateRevision:20160916141640
GitHash:7a8b7d5
```

https://github.com/CellProfiler/CellProfiler/blob/7a8b7d50f0a5ddaf64927c8ce79cebf32f869aa4/setup.py#L461

This turns out to be `v2.2.0`

**Comment by bethac07** [comment]
It is indeed 2.2.0
