### ISSUE TITLE
Error with importing cell-profilier pipelines

### ISSUE THREAD

**Issue by wagenrace** [broadinstitute/cell-health#159]
I tried to imported both pipelines from \0.download-data\cellprofiler_pipelines and both of them failed in both cell-profiler 2.2.0 and 4.1.3 but with different errors:

2.2.0: Error while loading None: Unknown mat file type, version 103, 105
4.1.3: Recieved HDF5 file header invalid

Action: file/import/pipeline from file

**Comment by gwaygenomics** [comment]
Interesting... @hkhawar - have you seen these errors before? We used version 2.2.0 in this project, so it is a bit strange to see this error. I wonder if it is a simple fix?

**Comment by bethac07** [comment]
Both of those pipelines are not actually pipeline files, they are some sort of HTML; I'm not sure how the pipeline files were added to this repo but I think you need to return to the source.

**Comment by gwaygenomics** [comment]
oh nice, seems like it's an easy fix then, thanks @bethac07.

@wagenrace - the actual analysis pipeline appears to be here: https://github.com/broadinstitute/imaging-platform-pipelines/blob/71b3e1a56916185d5bfb0d6f4ce99a43d240bbe6/cellpainting_a549_20x_phenix_bin1/analysis.cppipe

and the actual illum pipeline is here: https://github.com/broadinstitute/imaging-platform-pipelines/blob/71b3e1a56916185d5bfb0d6f4ce99a43d240bbe6/cellpainting_a549_20x_phenix_bin1/illum.cppipe

I'll add the actual files here in a pull request soon.

**Comment by gwaygenomics** [comment]
Added in #160
