### ISSUE TITLE
Machine Learning Covariate Features

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#23]
I need to consider adding covariate features to the model:

* Plate
* Cell Line

**Comment by gwaygenomics** [comment]
This was brought up again - time to adjust for these variables!

Particularly in regards to the distribution of cell health target variables, @shntnu and I determined that they are confounded by cell type. We tested a couple features (ROS example below) and the bimodality appears to be entirely driven by cell type.

![Screen Shot 2019-07-31 at 4 28 48 PM](https://user-images.githubusercontent.com/7340421/62245783-4b45ea80-b3b0-11e9-9f3b-fda81c238fc7.png)

We decided to MAD scale (x_i - x_median) / x_mad

Pull request incoming!

**Comment by gwaygenomics** [comment]
cc @AnneCarpenter

**Comment by AnneCarpenter** [comment]
Ah, good, glad it was a simple explanation!

**Comment by gwaygenomics** [comment]
Note that in #36 I added a normalization to the cell health target variables `mad_scale`. I have since noticed that this implementation results in far more missing values than required.

This process (specifically `x_mad = median_absolute_deviation(x, nan_policy="omit")`) induced a bunch of divide by zero errors. I have since switched to a traditional z-score.

**Comment by shntnu** [comment]
> specifically `x_mad = median_absolute_deviation(x, nan_policy="omit")`) induced a bunch of divide by zero errors

For our notes, this is because >=50% of the observations are identical e.g.
```r
> mad(c(rep(rnorm(1), 11), rnorm(10)))
[1] 0
```
