### ISSUE TITLE
Investigate specific CRISPR genes

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#53]
Similar to #52 - Do any of the genes we CRISPR targeted produce known cell health phenotypes? Do we predict these with our models?

**Comment by gwaygenomics** [comment]
Dependent on #35

**Comment by gwaygenomics** [comment]
This note came up again at meeting 12/16

There was specific rationale for selecting these genes. Some genes were known to trigger certain phenotypes captured via cell health assays. We should determine what information we have about the genes. If I can't find anything, then I will ask Paquita.

**Comment by AnneCarpenter** [comment]
Paquita mentioned they have some annotations of the genes, documenting their expected behavior. I'm not sure how structured it is, but it may help identify positive controls.

**Comment by gwaygenomics** [comment]
addressed in #141
