### ISSUE TITLE
Model Performance Varies across Cell Lines

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#61]
Some cell lines might perform differently than others. Determine if this is the case.

**Comment by gwaygenomics** [comment]
## Regression MSE per cell health variable across cell lines

![cell_line_mse_differences](https://user-images.githubusercontent.com/7340421/65396241-598e0280-dd72-11e9-8bde-1e939936575c.png)

Real and shuffled cell line specific mean squared error for all 70 cell health target variables. Each point represents a single target variable. The point is colored by an ANOVA F statistic. The higher the F stat, the more different the predictions were across cell lines. In general, HCC44 has the best performance.

**Comment by gwaygenomics** [comment]
also see #64

**Comment by gwaygenomics** [comment]
In #75 I compare performance of all 70 Cell Health Models across the three cell lines assayed (A549, ES2, HCC44).

## Summary

In general, model performance is different across the three cell lines. It appears that model performance is most variable in the ES2 Cell Line.

It looks like there are three classes of models.

1. Model works reasonably well across cell lines
2. Model works well in ES2 but not well in A549 and HCC44
3. Model does not work

Next steps are not immediately clear to me. We could only select models from group 1 above to pursue in repurposing hub. Or, we could try to adjust out cell line. I'm leaning towards only using group 1 models.

cc @shntnu @AnneCarpenter 

## Mean Squared Error

![cell_line_mse_differences](https://user-images.githubusercontent.com/7340421/68225487-7eef6c80-ffbe-11e9-8d69-d45c9d65c492.png)

## R Squared

![cell_line_rsquared_differences](https://user-images.githubusercontent.com/7340421/68225703-d4c41480-ffbe-11e9-89aa-365f234e5fb5.png)

## Linked Target Variables

Note the domain of Rsquared is [-inf, 1]. See #40 for more details. The "squared" part is confusing!

### All

![cell_line_differences_target_linked_full](https://user-images.githubusercontent.com/7340421/68225730-e0174000-ffbe-11e9-9a7c-4d3e7892a5a6.png)

### Subset

![cell_line_differences_target_linked_subset](https://user-images.githubusercontent.com/7340421/68225744-e73e4e00-ffbe-11e9-8f10-cd155336e076.png)

**Comment by shntnu** [comment]
> We could only select models from group 1 above to pursue in repurposing hub

@gwaygenomics Repurposing compounds were profiled in A549. So I'd lean towards using the models that did well in that cell line alone.

Are you ranking based on test error (with shuffle=FALSE)?

**Comment by AnneCarpenter** [comment]
(a) If I am looking at R squared plots correctly (the ones marked "Within Cell Line R Squared..." on x axis), it doesn't look like very many data points are outside the range seen for shuffled data so that is concerning whether there is a very large number worth pursuing at all? But then in the lower plots with color (labeled All and Subset, but I don't know what those labels mean) it seems the R squared is pretty nice for shuffle=false in test set. So I'm not sure how to reconcile those results, I need more data labels I think!

(b) Do we know anything about ES2 relative to the other two cell lines that might explain it being better than the others? Is there anything remarkable to note about it?

**Comment by gwaygenomics** [comment]
In #79 I rank models based on performance in A549. This might clear some stuff up about which models to pursue.

## All models

Regression model performance in test set (shuffled vs. real)

![ranked_models_A549_with_shuffle](https://user-images.githubusercontent.com/7340421/69277149-bf014280-0bad-11ea-882c-8af038050ea6.png)

## Top Models in A549

![ranked_models_A549](https://user-images.githubusercontent.com/7340421/69277291-08ea2880-0bae-11ea-8dc2-f5a762c65071.png)

Looks like a handful of models are worth pursuing and we should focus on applying these to the repurposing hub data.

I will also have to do a similar analysis using classification algorithms (also after addressing #78 ).

**Comment by gwaygenomics** [comment]
> (b) Do we know anything about ES2 relative to the other two cell lines that might explain it being better than the others? Is there anything remarkable to note about it?

I don't know... maybe it has the highest variance across all cell painting features, so the models were able to better rely on these samples for model training? I split this issue off to discuss in #80
