### ISSUE TITLE
Predicting Cell Health Dyes

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#68]
In #67 I added visualizations that demonstrate model performance on cell health features when predicting certain dyes. I provide results and interpretations below.

## Regression Performance - Training vs. Testing

![performance_summary_rsquared_assay](https://user-images.githubusercontent.com/7340421/66358761-56823d00-e942-11e9-8a2b-40e0efb9fac0.png)

Lots of cell health phenotypes captured with specific dyes are predicted consistently well. For example, DRAQ7-based phenotypes are predicted well, as are many gH2Ax-based phenotypes. pH3-based phenotypes are not predicted well. Also, as a negative control, the CRISPR efficiencies are not predicted well in training or in testing. Cell Painting will not capture CRISPR efficiency, and, therefore, should not be a predictable phenotype. 

## Comparing Regression to Classification Models

![performance_summary_assay_classification_vs_regression](https://user-images.githubusercontent.com/7340421/66358953-1079a900-e943-11e9-8d3b-2055be9f0180.png)

Interestingly, some phenotypes that cannot be predicted with regression, have good performance with a classification model. This suggests that some phenotypes are more susceptible to noisy intermediate values, and outliers are more informative of biology (see example of `vb_percent_all_late_apoptosis` below.

The specific phenotypes are not visualized in this figure, but, in order of AUC (decreasing performance):

```
'vb_percent_all_late_apoptosis'
'cc_g2_ph3_pos_high_n_spots_h2ax_mean'
'vb_percent_all_apoptosis'
'cc_cc_high_n_spots_h2ax_mean'
'cc_g1_high_n_spots_h2ax_mean'
'vb_percent_all_early_apoptosis'
'cc_edu_pos_high_n_spots_h2ax_mean'
'cc_g2_ph3_neg_n_spots_mean'
'cc_mitosis_ph3_neg_n_spots_mean'
```

## Classifying All Late Apoptosis (Example)

![vb_percent_all_late_apoptosis_dist](https://user-images.githubusercontent.com/7340421/66359366-d0b3c100-e944-11e9-926e-56c95976d03c.png)

![vb_percent_all_late_apoptosis_performance](https://user-images.githubusercontent.com/7340421/66359413-f9d45180-e944-11e9-8200-1b035e57c205.png)

## Summary

Certain dyes are predicted better than others, some phenotypes can be predicted with classification models much better than regression models.

**Comment by gwaygenomics** [comment]
cc @shntnu @AnneCarpenter

**Comment by AnneCarpenter** [comment]
Interesting - one comment on the example you show "All Late Apoptosis":  I think for classification models we would want the threshold to separate the two classes to be much higher, like 0.5 for the example, such that the majority of samples are negative and there are a handful of positives - I think that is what is actually going on in this instance. We could select the threshold in a systematic fashion, maybe something like Otsu's threshold would work. Better yet, a model that assumes most samples are negative and some subset are positive so it'd be a mixture of those two gaussians.
