### ISSUE TITLE
Change classification binarization

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#78]
Currently, we only calculate the median and separate out high vs. low values to symbolize 1 vs. 0 for all cell health classification models. We should design a better way to binarize. Perhaps using otsu thresholding or something similar.

**Comment by gwaygenomics** [comment]
Discussed at profiling checkin - can simply use above 2 standard deviations.

I will use this issue to document which models this might be useful for.

**Comment by gwaygenomics** [comment]
## Summary

I completed the classification analysis with updated labels, and I made several interesting observations.

In summary, I am not confident that using classification models is a valid approach given the limitations of the data. I outline my concerns below.

Thoughts and comments welcome! cc @AnneCarpenter @shntnu 

## Procedure

Consider any sample with 1.5 standard deviations above the mean of each individual cell health measurement as a positive sample. Anything below 1.5 stddev above is a negative sample. I retained the specific value identified in training and applied it to testing. Example below:

![vb_ros_mean_dist_modz](https://user-images.githubusercontent.com/7340421/72646714-c2fad800-3944-11ea-958b-e8aac047fbd0.png)

As expected, this resulted in many fewer examples in the positive class, especially in the test set. In fact, some cell health models did not have any positive examples. I did not fit models that had too few samples. I defined a cutoff below.

![classification_model_cutoff_modz](https://user-images.githubusercontent.com/7340421/72646828-081f0a00-3945-11ea-981d-6d22573268a9.png)

It is also important to note that the number of models that we were able to train is different depending on the normalization used. (☝️ `modz`) and (👇 `median`)

![classification_model_cutoff_median](https://user-images.githubusercontent.com/7340421/72646913-3d2b5c80-3945-11ea-9184-8d182350f5e5.png)

I trained all classification models as previously defined (#38 )

## Results

In aggregate, results look great for many variables (see below).
However, even though training and testing performance was generally high, the shuffled data performance jumped all over the place.

### MODZ

![classification_summary_modz](https://user-images.githubusercontent.com/7340421/72647012-7f549e00-3945-11ea-944d-082ea560397f.png)

### Median

![classification_summary_median](https://user-images.githubusercontent.com/7340421/72647084-ab701f00-3945-11ea-9f2c-c1b6089cefb2.png)

## Cell Line Specific Performance

As we did with the regression models (#44 ), I also split out classification performance for A549 independently (since the Repurposing Hub data is also A549).

The classification models suffer _even greater_ from low sample sizes when splitting out by cell line (especially since ES2 had the biggest phenotypic effect from CRISPR perturbations, see #80 ). The low sample size does not allow us to reliably determine expected performance in a new dataset.

![ranked_models_A549_modz_classification](https://user-images.githubusercontent.com/7340421/72647331-4d900700-3946-11ea-83eb-e559753b32f9.png)

To me, it looks like the shuffled performance jumps around too much to be reliable. I am also very suspicious of the models that claim to be making perfect predictions!

We do not see this potential inflation in the regression models:

![ranked_models_A549_modz](https://user-images.githubusercontent.com/7340421/72647399-7f08d280-3946-11ea-81a9-6063aa70bfdf.png)

(note: modz transform and R^2 < 0 truncated to zero)

**Comment by shntnu** [comment]
@gwaygenomics and I discussed – classification results being poor is not surprising given that we are throwing out a bulk of the data by the binarization strategy (1.5 s.d). No other binarization strategy would be meaningful. 

The good news is that regression works, and A549 results look good. 

@gwaygenomics will make slides for the meeting with Paquita et al. and we will discuss more then.
