### ISSUE TITLE
Visualizing Model Coefficients (Cell Painting Features)

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/cell-health#97]
There are a couple different ways to visualize model coefficients that are output from the cell health machine learning models. Currently, I visualize model coefficients based on model coefficients (per cell painting feature importance score) in aggregate across models (see #64). 

This visualization scheme is not very informative. Instead, [Rohban et al. 2017](https://elifesciences.org/articles/24060) describe several alternative methods. I will use this issue to document various methods and determine which one would work best for this project.

**Comment by gwaygenomics** [comment]
## Strategies

Based on strategies in [Rohban et al. 2017](https://elifesciences.org/articles/24060).

1. Create a "Feature Grid"

This involves grouping features together based on the type of measurement

**Comment by gwaygenomics** [comment]
I will present model coefficients for every model in some sort of automatically generated figure layout

**Comment by shntnu** [comment]
In #123 @gwaygenomics showed an example of how the model can be visualized via cell images.

This comment is a bookmark so I remember to add feedback here vs the PR

**Comment by AnneCarpenter** [comment]
I believe I’ve made other comments about this cell view... possibly in a slide deck somewhere?

**Comment by gwaygenomics** [comment]
> I believe I’ve made other comments about this cell view... possibly in a slide deck somewhere?

It's all in slack 😹 -  I will copy here

## Conversation

> GW: is this informative at all? How should I be thinking about a figure like this? The ultimate goal is to show, visually, the model predictions (albeit made on aggregate profiles) in single cells to see if anything jumps out. (In this case we were looking for RNA localization at nucleolus)

>DS: With so many image panels it's not immediately clear what I'm supposed to be looking at. It might benefit from some arrows or something demonstrating the key feature of interest, but alone I'm not sure there's an obvious trend as you move from left to right... Unless I'm totally misunderstanding it

> DS: The dominating visual feature is cell density, so to the eye I think that distracts quite a lot

> GW: this is helpful, thanks. I have next to zero experience looking at these types of figures. So it is very helpful to see how experts do and what ya’ll look for

> BC: The cells in columns 1 and 4 are also dead- were these randomly sampled, or "most representative"?

> GW: randomly sampled. also, cool to know those are dead cells. For a while I was trying to troubleshoot if my data structures were saving the wrong picture for certain channel/perturbations. it seems relatively straightforward to detect dead cells then... if we are interested in honing in on the "before-death" effects of perturbations, would it be worth filtering obviously dead cells from profile aggregation? (it wouldn't make sense if we think the death is the super important part of the profile) it also seems like viability-based phenotypes dominate after profile aggregation. I wonder if this would be the case if we remove dead cells. Maybe then more subtle phenotypes can get enough space to shine :sunny:

> BC: I think if possible, we want to show ideally the "most representative", not random.
It's definitely possible that removing dead cells would make the phenotype space clearer- AFAIK that's not an experiment we've ever tried.

> AC: I assume you are showing a random cell from a sample that scored high vs low? Because I feel like I want to see a sampling at each score rather than just one cell. I’m on my phone but it’s hard to see much trend, though in combination with the info about which features and channels are important, it might be easier to know what to attend to. Can you score single cells?

> GW: 
>> I assume you are showing a random cell from a sample that scored high vs low?

> Yep

>> Because I feel like I want to see a sampling at each score rather than just one cell.

> :thumbsup: I figured

>> though in combination with the info about which features and channels are important, it might be easier to know what to attend to.

>yeah! good point

>>Can you score single cells?

>Yeah!!! This is the ultimate goal, as was proposed in aim 3 of my K99. I do think it is beyond the scope of this project, but it is definitely in the foreground of the background of my thinking

**Comment by gwaygenomics** [comment]
FWIW, our strategy was used in [Schiff et al. 2020](https://doi.org/10.1101/2020.11.13.380576) and was the paper's first citation:

> To see if these best performing features held any mechanistic clues, we grouped them based on their type of measurement (e.g. shape, texture and intensity) and their origin by cellular compartment (cell, nucleus or cytoplasm) or image channel (DAPI, ER, RNA, AGP, and MITO)24. Such groupings resulted in features implicated in “area and shape”, “radial distribution” of signal within the RNA and AGP channels, and the “granularity” of signal in the mitochondria channel
